# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'config/routes.rb'

# Layout
Layout/LineLength:
  Max: 120

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Rails
Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/StrongParametersExpect:
  Exclude:
    - 'app/controllers/**/*'

# RSpec
RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Max: 5

RSpec/LetSetup:
  Exclude:
    - 'spec/system/**/*'

RSpec/AnyInstance:
  Enabled: false
