name: Homey Project Management CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: homey_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.2
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle config unset deployment
        bundle config unset frozen
        bundle install
        
    - name: Set up database
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/homey_test
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
        
    - name: Precompile assets
      env:
        RAILS_ENV: test
      run: |
        bundle exec rails tailwindcss:build
        bundle exec rails assets:precompile
        
    - name: Run tests
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/homey_test
        CI: true
      run: |
        bundle exec rspec
        
    - name: Run linters
      run: |
        bundle exec rubocop --fail-level fatal

  # Deployment job for Heroku
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      
      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
      
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: "homey-project-mgmt-prod"
        run: |
          # Check if app exists
          if ! heroku apps:info $HEROKU_APP_NAME &> /dev/null; then
            echo "Creating Heroku app $HEROKU_APP_NAME"
            heroku apps:create $HEROKU_APP_NAME
          fi
          
          # Deploy code
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
          
          # Run migrations
          heroku run rake db:migrate --app $HEROKU_APP_NAME
